package interfaces;

import Cardspackage.Minions.BigGameHunter;
import Cardspackage.Minions.BluegillWarrior;
import Cardspackage.Minions.ChillwindYeti;
import Cardspackage.Minions.CurioCollector;
import Cardspackage.Minions.Dreadscale;
import Cardspackage.Minions.Gruul;
import Cardspackage.Minions.HighPriestAmet;
import Cardspackage.Minions.KronxDragonhoof;
import Cardspackage.Minions.LeperGnome;
import Cardspackage.Minions.MurlocRaider;
import Cardspackage.Minions.MurlocWarleader;
import Cardspackage.Minions.OasisSnapjaw;
import Cardspackage.Minions.Sandbinder;
import Cardspackage.Minions.Sathrovarr;
import Cardspackage.Minions.SeaGiant;
import Cardspackage.Minions.SecurityRover;
import Cardspackage.Minions.Shieldbearer;
import Cardspackage.Minions.SwampKingDred;
import Cardspackage.Minions.TheBlackKnight;
import Cardspackage.Minions.ThrallmarFarseer;
import Cardspackage.Minions.TombWarden;
import Cardspackage.Spells.ArcaneShot;
import Cardspackage.Spells.AstralRift;
import Cardspackage.Spells.Backstab;
import Cardspackage.Spells.BookofSpecters;
import Cardspackage.Spells.FriendlySmith;
import Cardspackage.Spells.HolySmite;
import Cardspackage.Spells.LearnDraconic;
import Cardspackage.Spells.PharaohBlessing;
import Cardspackage.Spells.Polymorph;
import Cardspackage.Spells.Sprint;
import Cardspackage.Spells.StrengthinNumbers;
import Cardspackage.Spells.Swarmoflocusts;
import Cardspackage.Spells.gift;
import Cardspackage.Weapons.BattleAxe;
import Cardspackage.Weapons.BloodFury;
import Cardspackage.Weapons.HeavyAxe;

public interface Visitor {

		public void visitArcaneShot	(ArcaneShot m);
		public void visitAstralRift(AstralRift m);
		public void visitBackstab(Backstab m);
		public void visitBattleAxe(BattleAxe m);
		public void visitBigGameHunter(BigGameHunter m);
		public void visitBloodFury(BloodFury m);
		public void visitBluegillWarrior(BluegillWarrior m);
		public void visitBookofSpecters(BookofSpecters m);
		public void visitChillwindYeti(ChillwindYeti m);
		public void visitCurioCollector(CurioCollector m);
		public void visitDreadscale(Dreadscale m);
		public void visitFriendlySmith(FriendlySmith m);
		public void visitgift(gift m);
		public void visitGruul(Gruul m);
		public void visitHeavyAxe(HeavyAxe m);
		public void visitHighPriestAmet(HighPriestAmet m);
		public void visitHolySmite(HolySmite m);
		public void visitKronxDragonhoof(KronxDragonhoof m);
		public void visitLearnDraconic(LearnDraconic m);
		public void visitLeperGnome(LeperGnome m);
		public void visitMurlocWarleader(MurlocWarleader m);
		public void visitMurlocRaider(MurlocRaider m);
		public void visitOasisSnapjaw(OasisSnapjaw m);
		public void visitPharaohBlessing(PharaohBlessing m);
		public void visitPolymorph(Polymorph m);
		public void visitSandbinder(Sandbinder m);
		public void visitSathrovarr(Sathrovarr m);
		public void visitSeaGiant(SeaGiant m);
		public void visitSecurityRover(SecurityRover m);
		public void visitShieldbearer(Shieldbearer m);
		public void visitSprint(Sprint m);
		public void visitStrengthinNumbers(StrengthinNumbers m);
		public void visitSwampKingDred(SwampKingDred m);
		public void visitSwarmoflocusts(Swarmoflocusts m);
		public void visitTheBlackKnight(TheBlackKnight m);
		public void visitThrallmarFarseer(ThrallmarFarseer m);
		public void visitTombWarden(TombWarden m);	
}
