package interfaces;

import java.util.ArrayList;

import Cardspackage.Card;
import Cardspackage.Minions.BigGameHunter;
import Cardspackage.Minions.BluegillWarrior;
import Cardspackage.Minions.ChillwindYeti;
import Cardspackage.Minions.CurioCollector;
import Cardspackage.Minions.Dreadscale;
import Cardspackage.Minions.Gruul;
import Cardspackage.Minions.HighPriestAmet;
import Cardspackage.Minions.KronxDragonhoof;
import Cardspackage.Minions.LeperGnome;
import Cardspackage.Minions.MurlocRaider;
import Cardspackage.Minions.MurlocWarleader;
import Cardspackage.Minions.OasisSnapjaw;
import Cardspackage.Minions.Sandbinder;
import Cardspackage.Minions.Sathrovarr;
import Cardspackage.Minions.SeaGiant;
import Cardspackage.Minions.SecurityRover;
import Cardspackage.Minions.Shieldbearer;
import Cardspackage.Minions.SwampKingDred;
import Cardspackage.Minions.TheBlackKnight;
import Cardspackage.Minions.ThrallmarFarseer;
import Cardspackage.Minions.TombWarden;
import Cardspackage.Spells.ArcaneShot;
import Cardspackage.Spells.AstralRift;
import Cardspackage.Spells.Backstab;
import Cardspackage.Spells.BookofSpecters;
import Cardspackage.Spells.FriendlySmith;
import Cardspackage.Spells.HolySmite;
import Cardspackage.Spells.LearnDraconic;
import Cardspackage.Spells.PharaohBlessing;
import Cardspackage.Spells.Polymorph;
import Cardspackage.Spells.Sprint;
import Cardspackage.Spells.StrengthinNumbers;
import Cardspackage.Spells.Swarmoflocusts;
import Cardspackage.Spells.gift;
import Cardspackage.Weapons.BattleAxe;
import Cardspackage.Weapons.BloodFury;
import Cardspackage.Weapons.HeavyAxe;
import hero.Heros;
import playModel.Player;

public interface Visitor {

		public void visitArcaneShot	(ArcaneShot m, Object taeget, Player attackerP, Player targetP);
		public void visitAstralRift(AstralRift m, Object taeget, Player attackerP, Player targetP);
		public void visitBackstab(Backstab m, Object taeget, Player attackerP, Player targetP);
		public void visitBattleAxe(BattleAxe m, Object taeget, Player attackerP, Player targetP);
		public void visitBigGameHunter(BigGameHunter m, Object taeget, Player attackerP, Player targetP);
		public void visitBloodFury(BloodFury m, Object taeget, Player attackerP, Player targetP);
		public void visitBluegillWarrior(BluegillWarrior m, Object taeget, Player attackerP, Player targetP);
		public void visitBookofSpecters(BookofSpecters m, Object taeget, Player attackerP, Player targetP);
		public void visitChillwindYeti(ChillwindYeti m, Object taeget, Player attackerP, Player targetP);
		public void visitCurioCollector(CurioCollector m, Object taeget, Player attackerP, Player targetP);
		public void visitDreadscale(Dreadscale m, Object taeget, Player attackerP, Player targetP);
		public void visitFriendlySmith(FriendlySmith m, Object taeget, Player attackerP, Player targetP);
		public void visitgift(gift m, Object taeget, Player attackerP, Player targetP);
		public void visitGruul(Gruul m, Object taeget, Player attackerP, Player targetP);
		public void visitHeavyAxe(HeavyAxe m, Object taeget, Player attackerP, Player targetP);
		public void visitHighPriestAmet(HighPriestAmet m, Object taeget, Player attackerP, Player targetP);
		public void visitHolySmite(HolySmite m, Object taeget, Player attackerP, Player targetP);
		public void visitKronxDragonhoof(KronxDragonhoof m, Object taeget, Player attackerP, Player targetP);
		public void visitLearnDraconic(LearnDraconic m, Object taeget, Player attackerP, Player targetP);
		public void visitLeperGnome(LeperGnome m, Object taeget, Player attackerP, Player targetP);
		public void visitMurlocWarleader(MurlocWarleader m, Object taeget, Player attackerP, Player targetP);
		public void visitMurlocRaider(MurlocRaider m, Object taeget, Player attackerP, Player targetP);
		public void visitOasisSnapjaw(OasisSnapjaw m, Object taeget, Player attackerP, Player targetP);
		public void visitPharaohBlessing(PharaohBlessing m, Object taeget, Player attackerP, Player targetP);
		public void visitPolymorph(Polymorph m, Object taeget, Player attackerP, Player targetP);
		public void visitSandbinder(Sandbinder m, Object taeget, Player attackerP, Player targetP);
		public void visitSathrovarr(Sathrovarr m, Object taeget, Player attackerP, Player targetP);
		public void visitSeaGiant(SeaGiant m, Object taeget, Player attackerP, Player targetP);
		public void visitSecurityRover(SecurityRover m, Object taeget, Player attackerP, Player targetP);
		public void visitShieldbearer(Shieldbearer m, Object taeget, Player attackerP, Player targetP);
		public void visitSprint(Sprint m, Object taeget, Player attackerP, Player targetP);
		public void visitStrengthinNumbers(StrengthinNumbers m, Object taeget, Player attackerP, Player targetP);
		public void visitSwampKingDred(SwampKingDred m, Object taeget, Player attackerP, Player targetP);
		public void visitSwarmoflocusts(Swarmoflocusts m, Object taeget, Player attackerP, Player targetP);
		public void visitTheBlackKnight(TheBlackKnight m, Object taeget, Player attackerP, Player targetP);
		public void visitThrallmarFarseer(ThrallmarFarseer m, Object taeget, Player attackerP, Player targetP);
		public void visitTombWarden(TombWarden m, Object taeget, Player attackerP, Player targetP);	
}
